/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Rusoski (https://sketchfab.com/Rusoski)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/flowers-pack-2-2b1a4b57567b40c88a50a6551ac312ef
title: Flowers pack 2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function Model({ ...props }) {
  const group = useRef()

  useFrame(({clock}) => {
    const elapsedTime = Math.sin(clock.getElapsedTime()); 
      group.current.rotation.x = elapsedTime /45 ;
    
  });
  
  const { nodes, materials } = useGLTF('/flowerOut.gltf')
  return (
    <group {...props} dispose={null}>
      <group  ref={group}rotation={[Math.PI / 400, 34.99, -14.69]} scale={20.26}>
        <group position={[-12.61, -3, -11.2]} scale={10}>
          <mesh geometry={nodes.Plane000_0.geometry} material={materials.Flower4} />
        </group>
        <group position={[37.89, -2.25, -48.9]} rotation={[.89, -.1, -.738]} scale={14.88}>
          <mesh geometry={nodes.Plane002_0.geometry} material={materials.Flower4} />
        </group>
        <group  position={[-17.66, -19.25, -19.9]} rotation={[0, 0, 2.23]} scale={15.88}>
          <mesh geometry={nodes.Plane003_0.geometry} material={materials.Flower3} />
        </group>
        <group position={[-3.39, 8.25, -8]} rotation={[-.55, .2, -12.48]} scale={11.88}>
          <mesh geometry={nodes.Plane002_0.geometry} material={materials.Flower4} />
        </group>
        <group position={[28.39, -10.15, -28.2]} rotation={[25.2, -.38, -31.48]} scale={11.88}>
          <mesh geometry={nodes.Plane002_0.geometry} material={materials.Flower1} />
        </group> 
        <group position={[9.39, 15, -35]} rotation={[.2, .6, -19.48]} scale={18.88}>
          <mesh geometry={nodes.Plane002_0.geometry} material={materials.Flower2} />
        </group>
        <group position={[-16.39, 4.15, -15.5]} rotation={[0, -.2, -.48]} scale={8.88}>
          <mesh geometry={nodes.Plane003_0.geometry} material={materials.Flower2} />
        </group>
        <group position={[-22.39, 23.15, -25.4]} rotation={[-.8, -.02, -.28]} scale={8.88}>
          <mesh geometry={nodes.Plane003_0.geometry} material={materials.Flower4} />
        </group>
       
      </group>
    </group>
  )
}

useGLTF.preload('/flower.gltf')
