/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: kongle (https://sketchfab.com/minecraftnorge)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/mars-7b14d8d8a5b94626a4b2a8a4455297d6
title: Mars
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function Model({ ...props }) {
  const group = useRef()

  useFrame(({clock}) => {

    const elapsedTime = clock.getElapsedTime(); 
    group.current.rotation.y = -elapsedTime / 110;
 
    
  });
  const { nodes, materials } = useGLTF('/mars.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} position={[-525, 424, 818]} scale={[60, 60,60]} >
        <mesh geometry={nodes.Object_2.geometry} material={materials.moon} />
      </group>
    </group>
  )
}

useGLTF.preload('/mars.gltf')
