/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Akshat (https://sketchfab.com/shooter24994)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mercury-32347fa4ec1a4987b71f461a401d91c4
title: Mercury
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function Model({ ...props }) {
  const group = useRef();
  const rotationRef = useRef();
  const { nodes, materials } = useGLTF('/plutoOut.gltf');
  useFrame(({clock}) => {

    const elapsedTime = clock.getElapsedTime(); 
    group.current.rotation.y = -elapsedTime /104;
    rotationRef.current.rotation.z = elapsedTime/20;
    
  });
  return (
    <group ref={group} {...props} dispose={null} >
      <group rotation={[-Math.PI / 12, -3, -4]} position={[ 146, 420, 960]} scale={[.1,.1,.1]} ref={rotationRef}>
        <group rotation={[Math.PI / 2, 2, 12]}>
          <group rotation={[-Math.PI / 2, 12, 0]} scale={150}>
            <mesh geometry={nodes.Object_2.geometry} material={materials['moon']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mercury.gltf')
