/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: uperesito (https://sketchfab.com/uperesito)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/urano-b89a7d4c0f5147129b7fbac98ce70888
title: Urano
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function Model({ ...props }) {
  const group = useRef();
  const rotationRef = useRef();

  useFrame(({clock}) => {

    const elapsedTime = clock.getElapsedTime(); 
   
    group.current.rotation.y   = -elapsedTime/36;
    rotationRef.current.rotation.y = elapsedTime/ 5;
   
    

    
  });
  const { nodes, materials } = useGLTF('/uranus.gltf')
  return (
    <group ref={group} {...props} dispose={null} >
      <group rotation={[-Math.PI / 2, 0, 0]} position={[-134, 404, -1074]} scale={[.3,.3,.3]} ref={rotationRef}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-1.7, 0, 0]}>
            <mesh geometry={nodes.Esfera_Mat1_0.geometry} material={nodes.Esfera_Mat1_0.material} />
            <mesh geometry={nodes.Esfera_Mat1_0_1.geometry} material={nodes.Esfera_Mat1_0_1.material} />
            <mesh geometry={nodes.Esfera_Mat1_0_2.geometry} material={nodes.Esfera_Mat1_0_2.material} />
            <mesh geometry={nodes.Esfera_Mat1_0_3.geometry} material={nodes.Esfera_Mat1_0_3.material} />
            <mesh geometry={nodes.Esfera_Mat1_0_4.geometry} material={nodes.Esfera_Mat1_0_4.material} />
            <mesh geometry={nodes.Esfera_Mat1_0_5.geometry} material={nodes.Esfera_Mat1_0_5.material} />
            <mesh geometry={nodes.Esfera_Mat1_0_6.geometry} material={nodes.Esfera_Mat1_0_6.material} />
            <mesh geometry={nodes.Esfera_Mat1_0_7.geometry} material={nodes.Esfera_Mat1_0_7.material} />
          </group>
          <group rotation={[0.14, 0, 0]}>
            <group position={[-450, 50, 0]} rotation={[-0.27, 0, 0]}>
              <mesh geometry={nodes.Plano_Mat_0.geometry} material={materials.material} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/uranus.gltf')
